import static org.junit.Assert.*;

import java.util.Date;
import java.util.Vector;

import org.junit.Test;


public class LogicTest {
	@Test
	public void testStep1Status() {
		Event event = new Event();
		Logic tester = new Logic(event, new DataManager());
		assertEquals("Result", 0, tester.step1Status());
		
		event.setEventName("event name");
		assertEquals("Result", 1, tester.step1Status());
		
		MyCalendar start = new MyCalendar();
		start.setYear(2012);
		event.setStartDateAndTime(start);
		assertEquals("Result", 1, tester.step1Status());
		
		MyCalendar end = new MyCalendar();
		end.setYear(2012);
		event.setEndDateAndTime(end);
		assertEquals("Result", 1, tester.step1Status());
		
		event.setEventType(EventType.ANNIVERSARY);
		assertEquals("Result", 1, tester.step1Status());
		
		event.setMealType(MealType.DINNER);
		assertEquals("Result", 1, tester.step1Status());
		
		event.setEventDescription("event description");
		assertEquals("Result", 1, tester.step1Status());
		
		event.setEventBudget(1000);
		assertEquals("Result", 2, tester.step1Status());
	}
	
	@Test
	public void testStep2Status(){
		Event event = new Event();
		Logic tester = new Logic(event, new DataManager());
		assertEquals("Result", 0, tester.step2Status());
		
		event.setGuestList(new Vector<Guest>());
		assertEquals("Result", 0, tester.step2Status());
		
		event.getGuestList().add(new Guest());
		assertEquals("Result", 1, tester.step2Status());
		
		event.getGuestList().get(0).setName("name");
		event.getGuestList().get(0).setGroup("group");
		event.getGuestList().get(0).setGender(Gender.MALE);
		event.getGuestList().get(0).setEmailAddress("email");
		event.getGuestList().get(0).setDescription("description");
		event.getGuestList().get(0).setContactNumber("12323");
		event.setGuestListFinalised(true);
		assertEquals("Result", 3, tester.step2Status());
	}
	
	@Test
	public void testStep3Status(){
		Event event = new Event();
		Logic tester = new Logic(event, new DataManager());
		assertEquals("Result", 0, tester.step3Status());
		
		event.setProgrammeSchedule(new Vector<Programme>());
		assertEquals("Result", 0, tester.step3Status());
		
		event.getProgrammeSchedule().add(new Programme());
		assertEquals("Result", 1, tester.step3Status());
		
		event.getProgrammeSchedule().get(0).setStartTime(1000);
		event.getProgrammeSchedule().get(0).setEndTime(1200);
		event.getProgrammeSchedule().get(0).setInCharge("person");
		event.getProgrammeSchedule().get(0).setTitle("title");
		event.getProgrammeSchedule().get(0).setProgrammeDate("date");
		event.setProgrammeScheduleFinalised(true);
		assertEquals("Result", 3, tester.step3Status());
	}
	
	@Test
	public void testStep4Status(){
		Event event = new Event();
		Logic tester = new Logic(event, new DataManager());
		assertEquals("Result", 0, tester.step4Status());
		
		event.setSelectedHotelIdx(1);
		assertEquals("Result", 1, tester.step4Status());
	}
	
	@Test
	public void testSetEventType(){
		Event event = new Event();
		Logic tester = new Logic(event, new DataManager());
		
		tester.setEventType(-1);
		assertEquals("Result", null, event.getEventType());
		
		tester.setEventType(11);
		assertEquals("Result", null, event.getEventType());
		
		tester.setEventType(2);
		assertEquals("Result", EventType.AWARD_CEREMONY, event.getEventType());
	}
	
	@Test
	public void testGetEventType(){
		Event event = new Event();
		Logic tester = new Logic(event, new DataManager());
		
		event.setEventType(EventType.ANNIVERSARY);
		assertEquals("Result", 0, tester.getEventType());
		
		event.setEventType(null);
		assertEquals("Result", -1, tester.getEventType());
	}
	
	@Test
	public void testSetEventName(){
		//trivial
	}
	
	/*
	 * If we only call setEventStartDate by passing on a Date object that is generated by JCalendar, 
	 * we can be sure no garbage data is passed in.
	 */
	@SuppressWarnings("deprecation")
	@Test
	public void testSetEventStartDate(){
		Event event = new Event();
		Logic tester = new Logic(event, new DataManager());
		
		Date date = new Date(2012, 11, 12);
		tester.setEventStartDate(date);
		assertEquals("Result", 2012, event.getStartDateAndTime().getYear());
		assertEquals("Result", 11, event.getStartDateAndTime().getMonth());
		assertEquals("Result", 12, event.getStartDateAndTime().getDate());
	}
	
	@SuppressWarnings("deprecation")
	@Test
	public void testGetEventStartDate(){
		Event event = new Event();
		Logic tester = new Logic(event, new DataManager());
		
		MyCalendar calendar = new MyCalendar();
		calendar.setYear(2012);
		calendar.setMonth(11);
		calendar.setDate(30);
		event.setStartDateAndTime(calendar);
		assertEquals("Result", 2012, tester.getEventStartDate().getYear());
		assertEquals("Result", 11, tester.getEventStartDate().getMonth());
		assertEquals("Result", 30, tester.getEventStartDate().getDate());
		
		event.setStartDateAndTime(new MyCalendar());
		assertEquals("Result", null, tester.getEventStartDate());
	}
	
	@SuppressWarnings("deprecation")
	@Test
	public void testSetEventEndDate(){
		Event event = new Event();
		Logic tester = new Logic(event, new DataManager());
		
		Date date = new Date(2012, 11, 12);
		tester.setEventEndDate(date);
		assertEquals("Result", 2012, event.getEndDateAndTime().getYear());
		assertEquals("Result", 11, event.getEndDateAndTime().getMonth());
		assertEquals("Result", 12, event.getEndDateAndTime().getDate());
	}
	
	@SuppressWarnings("deprecation")
	@Test
	public void testGetEventEndDate(){
		Event event = new Event();
		Logic tester = new Logic(event, new DataManager());
		
		MyCalendar calendar = new MyCalendar();
		calendar.setYear(2012);
		calendar.setMonth(11);
		calendar.setDate(30);
		event.setEndDateAndTime(calendar);
		assertEquals("Result", 2012, tester.getEventEndDate().getYear());
		assertEquals("Result", 11, tester.getEventEndDate().getMonth());
		assertEquals("Result", 30, tester.getEventEndDate().getDate());
		
		event.setEndDateAndTime(new MyCalendar());
		assertEquals("Result", null, tester.getEventEndDate());
	}
	
	@Test
	public void testCheckDate(){
		Event event = new Event();
		Logic tester = new Logic(event, new DataManager());
		
		//start before end
		MyCalendar start = new MyCalendar();
		start.setYear(2012);
		start.setMonth(4);
		start.setDate(3);
		event.setStartDateAndTime(start);
		
		MyCalendar end = new MyCalendar();
		end.setYear(2012);
		end.setMonth(4);
		end.setDate(4);
		event.setEndDateAndTime(end);
		
		assertEquals("Result", true, tester.checkDate());
		
		end.setDate(1);
		end.setMonth(5);
		assertEquals("Result", true, tester.checkDate());
		
		end.setMonth(3);
		end.setYear(2013);
		assertEquals("Result", true, tester.checkDate());
		
		//start same as end
		end.setYear(2012);
		end.setMonth(4);
		end.setDate(3);
		assertEquals("Result", true, tester.checkDate());
		
		//start after end
		start.setDate(4);
		assertEquals("Result", false, tester.checkDate());
		
		start.setMonth(5);
		assertEquals("Result", false, tester.checkDate());
		
		start.setYear(2013);
		assertEquals("Result", false, tester.checkDate());
	}
	
	@SuppressWarnings("deprecation")
	@Test
	public void testSetDateList(){
		//precondition, start date is before end date
		Event event = new Event();
		Logic tester = new Logic(event, new DataManager());
		
		tester.setDateList(new Date(112, 10, 2), new Date(112, 10, 2));
		assertEquals("Results", 1, event.getDateList().size());
		assertEquals("Results", 1, event.getDateListStoredAsMyCalendarObject().size());
		assertEquals("Results", "1 Nov 2012 ", event.getDateList().get(0));	//Java Date stores 2012 as 2012 - 1900 etc.
		assertEquals("Results", 112, event.getDateListStoredAsMyCalendarObject().get(0).getYear());
		assertEquals("Results", 10, event.getDateListStoredAsMyCalendarObject().get(0).getMonth());
		assertEquals("Results", 2, event.getDateListStoredAsMyCalendarObject().get(0).getDate());	
	}
	
	@Test
	public void testGetGuestNameList(){
		
	}
	
	@Test
	public void testSetGuestInfo(){
		
	}
	
	@Test
	public void testCompletedGuestFields(){
		
	}
	
	@Test
	public void testGetProgrammeSchedule(){
		
	}
	
	@Test
	public void testSetProgrammeInfo(){
		
	}
	
	@Test
	public void testCompletedProgrammeFields(){
		
	}
	
	@Test
	public void testHotelSuggest(){
		
	}
	
	@Test
	public void testGuestSuggestedHOtelsNames(){
		
	}
	
	@Test
	public void testGetHotelInformation(){
		
	}
	
	@Test
	public void testGetSelectedHotelPrice(){
		
	}
	
	@Test
	public void testUpdateArrangementIndex(){
		
	}
	
	@Test
	public void testGetArrangement(){
		
	}
	
	@Test
	public void testGetExpenseList(){
		
	}
	
	@Test
	public void testSetExpenseInfo(){
		
	}
	
	@Test
	public void testCompletedExpenseFields(){
		
	}
}